### PR TITLE
fixed Potentially unwanted behaviour in ReplaceIgnoreCase

### LINKED ISSUE #136: Potentially unwanted behaviour in ReplaceIgnoreCase
The extension method  `public static string ReplaceIgnoreCase(this string input, string pattern, string replacement)` in src/TinyHelpers/Extensions/StringExtensions.cs is accepting a pattern parameter and is using is as a Regex to perform the case-insensitive replacement. However, the name of the method doesn't explicitly say that a regex will be used, and this might lead to potential unwanted results with some specific inputs. A possible implementation might be a facade to the method `public string Replace (string oldValue, string? newValue, StringComparison comparisonType);` where the comparisonType is `StringComparison.OrdinalIgnoreCase`, as it was done for the other methods in the same class, or sanitizing the pattern input with `Regex.Escape`. The `Replace` method overload that accepts the comparisonType in the string class is not available in netstandard2.0 but is part of netstandard2.1.

### PR DESCRIPTION
**Pull request by nicolaparo**
resolved #136 , by escaping the `pattern` parameter before performing the regex replacement

### CODE REVIEW

File: src/TinyHelpers/Extensions/StringExtensions.cs [hunk 1]
```diff
@@ -17,8 +17,15 @@ public static bool EndsWithIgnoreCase(this string? a, string b)
     public static bool ContainsIgnoreCase(this string? a, string b)
         => a?.IndexOf(b, StringComparison.OrdinalIgnoreCase) >= 0;
 
+    /// <summary>
+    /// Returns a new string in which all occurrences of a specified string in the current instance are replaced with another specified string, ignoring the letter casing.
+    /// </summary>
+    /// <param name="input">The original string</param>
+    /// <param name="pattern">The string to be replaced, case insentive.</param>
+    /// <param name="replacement">The string to replace all occurrences of <paramref name="pattern"/> </param>
+    /// <returns></returns>
```
Comment (marcominerva) [inline src/TinyHelpers/Extensions/StringExtensions.cs:26]: You should complete the XML Documentation in the `result ` tag.

**Review by marcominerva — CHANGES_REQUESTED** [review]

File: src/TinyHelpers/Extensions/StringExtensions.cs (hunk 1 above)
Comment (nicolaparo) [reply src/TinyHelpers/Extensions/StringExtensions.cs]: Sorry, I forgot. Added now the XML documentation for the `returns` tag
